create table "public"."users_provider" (
    "user_id" uuid not null default auth.uid(),
    "provider_id" integer not null,
    "id" bigint generated by default as identity not null
);


alter table "public"."users_provider" enable row level security;

CREATE UNIQUE INDEX users_provider_pkey ON public.users_provider USING btree (id);

alter table "public"."users_provider" add constraint "users_provider_pkey" PRIMARY KEY using index "users_provider_pkey";

alter table "public"."users_provider" add constraint "public_users_provider_provider_id_fkey" FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE not valid;

alter table "public"."users_provider" validate constraint "public_users_provider_provider_id_fkey";

alter table "public"."users_provider" add constraint "public_users_provider_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."users_provider" validate constraint "public_users_provider_user_id_fkey";

grant delete on table "public"."users_provider" to "anon";

grant insert on table "public"."users_provider" to "anon";

grant references on table "public"."users_provider" to "anon";

grant select on table "public"."users_provider" to "anon";

grant trigger on table "public"."users_provider" to "anon";

grant truncate on table "public"."users_provider" to "anon";

grant update on table "public"."users_provider" to "anon";

grant delete on table "public"."users_provider" to "authenticated";

grant insert on table "public"."users_provider" to "authenticated";

grant references on table "public"."users_provider" to "authenticated";

grant select on table "public"."users_provider" to "authenticated";

grant trigger on table "public"."users_provider" to "authenticated";

grant truncate on table "public"."users_provider" to "authenticated";

grant update on table "public"."users_provider" to "authenticated";

grant delete on table "public"."users_provider" to "service_role";

grant insert on table "public"."users_provider" to "service_role";

grant references on table "public"."users_provider" to "service_role";

grant select on table "public"."users_provider" to "service_role";

grant trigger on table "public"."users_provider" to "service_role";

grant truncate on table "public"."users_provider" to "service_role";

grant update on table "public"."users_provider" to "service_role";


